from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Literal

# Lifecycle: pending → resolved.
ApprovalStatus = Literal["pending", "resolved"]

# Semantic outcome of a resolved approval.
ApprovalDecision = Literal["approved", "needs_changes", "rejected"]


@dataclass(frozen=True)
class ApprovalRequest:
    """Immutable snapshot of an invoice approval request.

    Created when the agent registers a new approval; replaced (not mutated)
    when a decision is recorded.

    Fields
    ------
    approval_id:
        Opaque identifier generated by the OpenClaw agent.  Embedded in the
        public approve/reject URLs so the browser can resolve the record.
    invoice_case_id:
        Internal case identifier used by the OpenClaw agent as its session key.
    pdf_path:
        Checkpoint path to the invoice PDF; forwarded verbatim to OpenClaw
        in the webhook resume message.
    invoice_number:
        Human-readable Xero invoice number shown on the approval page.
    supplier_name:
        Supplier name shown on the approval page.
    approve_url / reject_url:
        Public URLs generated by the agent; stored for reference.
    status:
        Lifecycle state: pending → resolved.
    decision:
        Semantic outcome once resolved: approved | needs_changes | rejected.
        None while pending.
    note:
        Optional free-text note supplied by the reviewer.  Required when
        decision is needs_changes.
    created_at:
        UTC datetime when the approval was first registered.
    decided_at:
        UTC datetime when a decision was recorded; None while pending.
    decision_source:
        Free-form label identifying who/what submitted the decision
        (e.g. "web_form").  None while pending.
    webhook_sent_at:
        UTC datetime when the OpenClaw webhook call was attempted.
    webhook_result:
        "ok" on success; short error description on failure.  None while
        pending.  Stored so recovery can be attempted later if needed.
    """

    approval_id: str
    invoice_case_id: str
    pdf_path: str
    invoice_number: str
    supplier_name: str
    approve_url: str
    reject_url: str
    status: ApprovalStatus
    created_at: datetime  # UTC-aware
    decision: ApprovalDecision | None = None
    note: str | None = None
    decided_at: datetime | None = None  # UTC-aware
    decision_source: str | None = None
    webhook_sent_at: datetime | None = None  # UTC-aware
    webhook_result: str | None = None
